"""rewriteMenu

Revision ID: 893be07b82e9
Revises: a403c79ce55c
Create Date: 2024-08-26 15:37:31.627538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '893be07b82e9'
down_revision: Union[str, None] = 'a403c79ce55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menutable',
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nodeId', sa.Integer(), nullable=False),
    sa.Column('menuName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menuType', sa.Integer(), nullable=False),
    sa.Column('routeName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routePath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('i18nKey', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('iconType', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('hideInMenu', sa.Boolean(), nullable=False),
    sa.Column('multiTab', sa.Boolean(), nullable=False),
    sa.Column('keepAlive', sa.Boolean(), nullable=False),
    sa.Column('href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('fixedIndexInTab', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.Boolean(), nullable=False),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('interfaces', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_test_menu_identifier', table_name='test_menu')
    op.drop_index('ix_test_menu_name', table_name='test_menu')
    op.drop_index('ix_test_menu_nodeId', table_name='test_menu')
    op.drop_table('test_menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_menu',
    sa.Column('createTime', mysql.DATETIME(), nullable=False),
    sa.Column('updateTime', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('identifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('nodeId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_test_menu_nodeId', 'test_menu', ['nodeId'], unique=False)
    op.create_index('ix_test_menu_name', 'test_menu', ['name'], unique=False)
    op.create_index('ix_test_menu_identifier', 'test_menu', ['identifier'], unique=True)
    op.drop_table('menutable')
    # ### end Alembic commands ###
