"""rewriteMenu

Revision ID: 906d5f8e6d09
Revises: 893be07b82e9
Create Date: 2024-08-26 15:38:50.831413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '906d5f8e6d09'
down_revision: Union[str, None] = '893be07b82e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_menu',
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nodeId', sa.Integer(), nullable=False),
    sa.Column('menuName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menuType', sa.Integer(), nullable=False),
    sa.Column('routeName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routePath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('i18nKey', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('iconType', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('hideInMenu', sa.Boolean(), nullable=False),
    sa.Column('multiTab', sa.Boolean(), nullable=False),
    sa.Column('keepAlive', sa.Boolean(), nullable=False),
    sa.Column('href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('fixedIndexInTab', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.Boolean(), nullable=False),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('interfaces', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menutable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menutable',
    sa.Column('createTime', mysql.DATETIME(), nullable=False),
    sa.Column('updateTime', mysql.DATETIME(), nullable=False),
    sa.Column('component', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('nodeId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menuName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('menuType', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routeName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('routePath', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('i18nKey', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('iconType', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hideInMenu', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('multiTab', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('keepAlive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('href', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('constant', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fixedIndexInTab', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homepage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('query', mysql.JSON(), nullable=True),
    sa.Column('buttons', mysql.JSON(), nullable=True),
    sa.Column('interfaces', mysql.JSON(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('test_menu')
    # ### end Alembic commands ###
