"""update

Revision ID: 98738b33b4dc
Revises: eccc2ccde04f
Create Date: 2024-09-10 14:57:38.014634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98738b33b4dc'
down_revision: Union[str, None] = 'eccc2ccde04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('buttonCodes', sa.JSON(), nullable=True))
    op.add_column('test_role', sa.Column('interfaceCodes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_role', 'interfaceCodes')
    op.drop_column('test_role', 'buttonCodes')
    # ### end Alembic commands ###
