"""update

Revision ID: eccc2ccde04f
Revises: 906d5f8e6d09
Create Date: 2024-09-10 11:24:26.306997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eccc2ccde04f'
down_revision: Union[str, None] = '906d5f8e6d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test_menu', ['routePath'])
    op.add_column('test_role', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('test_role', sa.Column('menuIds', sa.JSON(), nullable=True))
    op.drop_column('test_role', 'identifierList')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('identifierList', mysql.JSON(), nullable=True))
    op.drop_column('test_role', 'menuIds')
    op.drop_column('test_role', 'status')
    op.drop_constraint(None, 'test_menu', type_='unique')
    # ### end Alembic commands ###
